### ISSUE TITLE
Project maintainers and future roadmap

### ISSUE THREAD

**Issue by ghaberek** [ghaberek/omada-api#16]
## Maintainers

As mentioned in #12, to say I *maintain* this project may be an overstatement. I am not disinterested in it but I also don't have a lot of free time to stay on top of things regularly. I will gladly add anyone as a contributor to this project if they want. I just ask that you've already submitted at least one PR and that you have one or more other Python projects on GitHub. Please reply here if you're interested.

## Roadmap

I don't have a lot of specific intent or direction for this project but I would like to see a few things happen in time:

- [ ] Move existing comments to docstrings and add more/better info
- [ ] Extend docstrings with references/notes from official TP-LINK docs
- [ ] Generate documentation with Spinx or similar
- [ ] Build data classes for each entity type to make data access easier
- [ ] Refactor entity types into different modules (sites, clients, etc.)
- [ ] Add more bounds/value checking where required (settings, etc.)
- [ ] Condense most examples into a common CLI utility

**Comment by jsestrich** [comment]
I'm using this project in a load bearing way in my home network, so I'd happy to help out as a contributor if you're willing to have me!

If you accept my PR (https://github.com/ghaberek/omada-api/pull/12) I should be fairly close to meeting your requirements. I will fully admit python is not my primary language, but I'm very open to taking direction if I'm not following the style properly.
